id: P010776A7
initial_creation_type: ocr
source_metadata:
  volumes:
    0682aecf9adc407caf32d1ecc7a28f3f:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་ཡི་གེ་དྲུག་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
