id: DCA2B1427
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-05T06:52:14+00:00'
last_modified: '2022-05-26T12:15:31.603405+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9d2d:
      image_group_id: I1PD95882
      title: འཕགས་པ་ཡི་གེ་དྲུག་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      order: 37
      base_file: 9d2d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
